
GET http://localhost:5046/

###
GET http://localhost:5046/api/categories
###

POST http://localhost:5046/api/categories

###

PUT http://localhost:5046/api/categories

###

DELETE http://localhost:5046/api/categories


